spring:
  profiles:
    active: @runtimeActivatedEnv@
  application:
    name: springcloud-nacos-discovery-consumer
  cloud:
    nacos:
      discovery:
        server-addr:  @nacos.server.registry@

server:
  port: 10001


